CUDA_VISIBLE_DEVICES=1,2,4 python -m torch.distributed.run \
--nproc_per_node=3 \
--master_port 12326 \
downstream_phase/run_phase_training.py \
--batch_size 28 \
--epochs 50 \
--save_ckpt_freq 10 \
--model  surgformer_HTA \
--mixup 0.8 \
--cutmix 1.0 \
--smoothing 0.1 \
--lr 5e-4 \
--layer_decay 0.75 \
--warmup_epochs 5 \
--data_path data/M2CAI \
--eval_data_path data/M2CAI \
--nb_classes 8 \
--data_strategy online \
--output_mode key_frame \
--num_frames 16 \
--sampling_rate 4 \
--eval \
--pretrained_path /home/dlmanrique/Endovis/MICCAI2025/SOTAS/Surgformer/Surgformer-COLAS-2025/results/M2CAI/surgformer_HTA_M2CAI_0.0005_0.75_online_key_frame_frame16_Fixed_Stride_4/checkpoint-best-epoch6-acc1-74.65504649449527.pth \
--data_set M2CAI \
--data_fps 1fps \
--output_dir results/M2CAI \
--log_dir results/M2CAI \
--num_workers 10 \
--dist_eval \
--no_auto_resume \
--cut_black