CUDA_VISIBLE_DEVICES=3 python -m torch.distributed.run  \
--nproc_per_node=1 \
--master_port 12324 \
downstream_phase/run_phase_training.py \
--batch_size 8 \
--epochs 50 \
--save_ckpt_freq 10 \
--model surgformer_HTA \
--pretrained_path Pretrained_weights/TimeSformer_divST_8x32_224_K400.pyth \
--mixup 0.8 \
--cutmix 1.0 \
--smoothing 0.1 \
--lr 5e-4 \
--layer_decay 0.75 \
--warmup_epochs 5 \
--data_path data/Cholec80 \
--eval_data_path data/Cholec80 \
--nb_classes 7 \
--data_strategy online \
--output_mode key_frame \
--num_frames 16 \
--sampling_rate 4 \
--data_set Cholec80 \
--data_fps 1fps \
--output_dir results/Cholec80 \
--log_dir results/Cholec80 \
--num_workers 0 \
--dist_eval \
--no_auto_resume